name: CI-IE

on: 
  create:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
    steps:
      - name: Install NPM packages
        run: npm install
        
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
