name: CI-IE

on: 
  create:
    tags:
      - v*
jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
        run:
            shell: bash
    steps:
      - name: Set up Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '12.x'
          registry-url: 'https://npm.pkg.github.com/transformd-ltd'
        
      - name: Publish
        run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
